name: Python application

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: ./starter
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        working-directory: ./starter
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --format=github --select=E9,F63,F7,F82 --statistics .
          # default set of ruff rules with GitHub Annotations
          flake8 --format=github  .
      - name: Test with pytest
        working-directory: ./starter
        run: |
          pytest
